CREATE TABLE permissions (
  id SERIAL PRIMARY KEY,
  nama VARCHAR(100) NULL,
  menu_id INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);